name: develop-workflow
on:
  push:
    branches:
        - develop
  pull_request:
    branches:
        - develop
jods:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: wellcome step 
              run: echo "well come to action perform"
            - name: checkout Repository
              uses: actions/actions/checkout@v4
            - name: Basic Info
              run: |
                echo"Repository name is :${{github.repository}}"
                echo"Repository name is :${{github.owner}}"
                echo"Repository name is :${{github.event}}"